packages:
  - name: api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    functions:
      - name: get-data
        runtime: nodejs:18
        web: true
        limits:
          timeout: 60000
          memory: 256
      - name: create-booking
        runtime: nodejs:18
        web: true
        limits:
          timeout: 60000
          memory: 256
