name: claire-hamilton-website
region: nyc

# Web Service (Frontend - Static Site served via http-server)
services:
  - name: frontend
    github:
      repo: AntonyNeal/sw_website
      branch: main
    build_command: npm install && npm run build
    run_command: npm run start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: VITE_GA_MEASUREMENT_ID
        value: ${GA_MEASUREMENT_ID}
      - key: VITE_API_BASE_URL
        value: ${API_BASE_URL}
      - key: VITE_FUNCTIONS_URL
        value: ${FUNCTIONS_URL}
    routes:
      - path: /

# Domain configuration
domains:
  - domain: clairehamilton.com
    type: PRIMARY
  - domain: www.clairehamilton.com
    type: ALIAS
  - domain: clairehamilton.vip
    type: ALIAS
